deploy: simplify (?) deployment script

diff --git a/.github/workflows/docker-img.yml b/.github/workflows/docker-img.yml
--- a/.github/workflows/docker-img.yml
+++ b/.github/workflows/docker-img.yml
@@ -194,128 +194,84 @@ jobs:
           fi
         done
   
-  deploy-rc-worker-via-helm:
+  deploy-rc-via-helm:
     needs:
     - warmup-rc-at-helm
     - setup-envvar
+    if:  ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - uses: ./.github/workflows/composite-set-k8s-cred
+      with:
+        secrets: ${{ secrets.KUBECONFIG }}
+    - run: .helm/deployments/rc/deploy.sh
     
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - queue: "core"
-          resource: 'low'
-        - queue: "compounds"
-          resource: 'high'
-        - queue: "features"
-          resource: 'high'
-
-    if:  ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
-    uses: ./.github/workflows/deploy-worker-helm-v4.yml
-    with:
-      DEPLOYMENT_NAME: rc-worker-${{ matrix.queue }}
-      HELM_FILE: .helm/siibra-api-v4-worker
-      FALVOR: rc
-      QUEUE: ${{ needs.setup-envvar.outputs.version }}.rc.${{ matrix.queue }}
-      IMAGE_TAG: rc-worker
-      RESOURCE: ${{ matrix.resource }}
-      PULL_POLICY: Always
-    secrets:
-      KUBECONFIG: ${{ secrets.KUBECONFIG }}
-      
-  deploy-rc-worker-v4-via-helm:
-    needs:
-    - warmup-rc-at-helm
-    - setup-envvar
-
-    if:  ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
-    uses: ./.github/workflows/deploy-worker-helm-v4.yml
-    with:
-      DEPLOYMENT_NAME: rc-worker-v4
-      HELM_FILE: .helm/siibra-api-v4-worker
-      FALVOR: rc
-      QUEUE: ""
-      IMAGE_TAG: rc-worker-v4
-      WORKER_PATH: ""
-      PULL_POLICY: Always
-    secrets:
-      KUBECONFIG: ${{ secrets.KUBECONFIG }}
-  
-  deploy-rc-server-via-helm:
-    needs:
-    - warmup-rc-at-helm
-    - setup-envvar
-    if:  ${{ github.event_name == 'release' && contains(github.ref, 'rc') }}
-    uses: ./.github/workflows/deploy-server-helm-v4.yml
-    with:
-      DEPLOYMENT_NAME: rc-server
-      FALVOR: rc
-      IMAGE_TAG: rc-server
-      PULL_POLICY: Always
-    secrets:
-      KUBECONFIG: ${{ secrets.KUBECONFIG }}
 
   # prod
-  # copy-by-helm:
-  #   needs: setup-envvar
-  #   if:  ${{ github.event_name == 'release' && !contains(github.ref, 'rc') }}
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 15 # should not take more than 15 minutes to copy cache
-  #   steps:
-  #   - uses: actions/checkout@v4
-  #   - uses: ./.github/workflows/composite-set-k8s-cred
-  #     with:
-  #       secrets: ${{ secrets.KUBECONFIG }}
-  #   - name: 'set FROM_DIR TO_DIR'
-  #     run: |
-  #       VERSION=${{ needs.setup-envvar.outputs.version }}
+  copy-by-helm:
+    needs: setup-envvar
+    if:  ${{ github.event_name == 'release' && !contains(github.ref, 'rc') }}
+    runs-on: ubuntu-latest
+    timeout-minutes: 15 # should not take more than 15 minutes to copy cache
+    steps:
+    - uses: actions/checkout@v4
+    - uses: ./.github/workflows/composite-set-k8s-cred
+      with:
+        secrets: ${{ secrets.KUBECONFIG }}
+    - name: 'set FROM_DIR TO_DIR'
+      run: |
+        VERSION=${{ needs.setup-envvar.outputs.version }}
 
-  #       # TODO use label exclusively in the future
-  #       POD=$(kubectl get pod -l role=server -l app-flavor=rc -o json | jq -r '.items[0].metadata.name')
-  #       echo POD: $POD
+        # TODO use label exclusively in the future
+        POD=$(kubectl get pod -l role=server -l app-flavor=rc -o json | jq -r '.items[0].metadata.name')
+        echo POD: $POD
 
-  #       cache_str=$(kubectl exec $POD -- env | grep SIIBRA_CACHEDIR)
-  #       FROM_DIR=${cache_str//SIIBRA_CACHEDIR=/}
-  #       TO_DIR=${FROM_DIR//-rc/}
-  #       POD_NAME=copy-cache
+        cache_str=$(kubectl exec $POD -- env | grep SIIBRA_CACHEDIR)
+        FROM_DIR=${cache_str//SIIBRA_CACHEDIR=/}
+        TO_DIR=${FROM_DIR//-rc/}
+        POD_NAME=copy-cache
 
-  #       echo FROM_DIR: $FROM_DIR, TO_DIR: $TO_DIR, POD_NAME: $POD_NAME
+        echo FROM_DIR: $FROM_DIR, TO_DIR: $TO_DIR, POD_NAME: $POD_NAME
 
-  #       echo "FROM_DIR=$FROM_DIR" >> $GITHUB_ENV
-  #       echo "TO_DIR=$TO_DIR" >> $GITHUB_ENV
-  #       echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV
+        echo "FROM_DIR=$FROM_DIR" >> $GITHUB_ENV
+        echo "TO_DIR=$TO_DIR" >> $GITHUB_ENV
+        echo "POD_NAME=$POD_NAME" >> $GITHUB_ENV
 
-  #   - name: 'start container'
-  #     run: |
-  #       # delete pod before workflow, so that logs can be inspected
-  #       kubectl delete pod/$POD_NAME || echo "Pod pod/$POD_NAME not found." 
-  #       FROM_DIR=$FROM_DIR TO_DIR=$TO_DIR envsubst < .helm/adhoc/copy-cache.yaml | kubectl apply -f -
-  #   - name: 'Ensure copy completes'
-  #     run: |
-  #       while true
-  #       do
-  #         sleep 10
-  #         POD_PHASE=$(kubectl get pod $POD_NAME -o json | jq -r '.status.phase')
+    - name: 'start container'
+      run: |
+        # delete pod before workflow, so that logs can be inspected
+        kubectl delete pod/$POD_NAME || echo "Pod pod/$POD_NAME not found." 
+        FROM_DIR=$FROM_DIR TO_DIR=$TO_DIR envsubst < .helm/adhoc/copy-cache.yaml | kubectl apply -f -
+    - name: 'Ensure copy completes'
+      run: |
+        while true
+        do
+          sleep 10
+          POD_PHASE=$(kubectl get pod $POD_NAME -o json | jq -r '.status.phase')
 
-  #         echo Possible phases: Pending, Running, Succeeded, Failed, Unknown
-  #         echo Found phase: $POD_PHASE
+          echo Possible phases: Pending, Running, Succeeded, Failed, Unknown
+          echo Found phase: $POD_PHASE
 
-  #         if [[ "$POD_PHASE" == "Failed" ]] || [[ "$POD_PHASE" == "Unknown" ]]
-  #         then
-  #           exit 1
-  #         fi
+          if [[ "$POD_PHASE" == "Failed" ]] || [[ "$POD_PHASE" == "Unknown" ]]
+          then
+            exit 1
+          fi
 
-  #         if [[ "$POD_PHASE" == "Succeeded" ]]
-  #         then
-  #           exit 0
-  #         fi
-  #       done
+          if [[ "$POD_PHASE" == "Succeeded" ]]
+          then
+            exit 0
+          fi
+        done
 
-  # deploy-prod-via-helm:
-  #   needs: copy-by-helm
-  #   if:  ${{ github.event_name == 'release' && !contains(github.ref, 'rc') }}
-  #   uses: ./.github/workflows/deploy-helm.yml
-  #   with:
-  #     DEPLOYMENT_NAME: prod
-  #   secrets:
-  #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
+  deploy-prod-via-helm:
+    needs: copy-by-helm
+    if:  ${{ github.event_name == 'release' && !contains(github.ref, 'rc') }}
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - uses: ./.github/workflows/composite-set-k8s-cred
+      with:
+        secrets: ${{ secrets.KUBECONFIG }}
+    - run: .helm/deployments/prod/deploy.sh
+
